### ISSUE TITLE
NoSQL y MongoDB 101 - Nicolás Isnardi

### ISSUE THREAD

**Issue by nisnardi** [FreeCodeCampBA/charlas#1]
Nombre de la charla: 
NoSQL y MongoDB 101

Autor: 
Nicolás Isnardi
https://twitter.com/isnardi

Fecha: 
De Abril en adelante, fecha posible 23/04/2017

**Comment by nhsz** [comment]
Cambio la fecha al 30/4 por pedido de @nisnardi
