### ISSUE TITLE
Literales, Valores y Variables - Martin Scotta

### ISSUE THREAD

**Issue by eridal** [FreeCodeCampBA/charlas#2]
Nombre de la charla: **Literales, Valores y Variables**

Autor: **Martin Scotta**
https://github.com/eridal
https://twitter.com/eridal

Fecha:
Cuando gusten. Me propusieron 26/03/2017

**Comment by lndgalante** [comment]
Lo cambiamos para el Domingo 02 de Abril ya que este Viernes 24 de Marzo es feriado y tenemos poca concurrencia los fin de semanas largos.
