### ISSUE TITLE
TDD === NO BUGS - Gonzalo Gras Cantou

### ISSUE THREAD

**Issue by Guusy** [FreeCodeCampBA/charlas#28]
## Título de la charla:
TDD === NO BUGS

## Descripción:
Lo ideal seria separar la charla en 3 partes:

1) Introduccion teorica a TDD, para que sirve y sus ventajas.
2) Mini workshop haciendo tdd en node pelado
3) Mini workshop haciendo tdd en un aplicacion react con jest + enzyme

## Autor:
- Nombre: Gonzalo Gras cantou
- Twitter: https://twitter.com/teengountuitter
- Blog: -
- Sitio personal: -

**Comment by lndgalante** [comment]
Gracias @Guusy por esto! Necesitas que te ayudemos con algo en particular? 
Más adelante si podes pasarnos lo que te tomaría cada parte sería genial así tenemos un cronograma más detallado.

**Comment by Guusy** [comment]
A tomar coraje ! jajajaj
Voy a estar pensando un prototipo de charla en estos dias ! 🎉

**Comment by lndgalante** [comment]
Perfecto avisanos cualquier cosa, saludos!
