### ISSUE TITLE
Bluemix, un entorno de desarrollo - Facundo Martin Gordillo

### ISSUE THREAD

**Issue by FMGordillo** [FreeCodeCampBA/charlas#4]
## Título de la charla: 
Hackatones + IBM Cloud como entorno de desarrollo
## Descripción:
Estuve en muchas Hackatones, y el problema general es que no se llega con el tiempo estipulado. Quiero dar buenas prácticas, consejos, y mostrar Bluemix para agilizar el desarrollo.
Bluemix es una plataforma como servicio (PaaS) similar a Microsoft Azure y a AWS (Amazon Web Services). Como empleado de IBM, y desarrollador en aprendizaje, quería compartir esta plataforma ideal para hackatones. También el funcionamiento de los PaaS.
## Autor:
- Nombre: Facundo Martin Gordillo
- Twitter: @FMGordillo
- Blog: N/A
- Sitio personal: N/A (todavía)

**Comment by lndgalante** [comment]
Groso @FMGordillo te parece para Junio ?

**Comment by FMGordillo** [comment]
Me parece perfecto @Fenwil !

**Comment by lndgalante** [comment]
Tenes para elegir: 

- Domingo 4 de Junio

- Domingo 11 de Junio

- Domingo 18 de Junio

- Domingo 25 de Junio

**Comment by FMGordillo** [comment]
4 me parece bien, no es época de finales según recuerdo

**Comment by nhsz** [comment]
Es una plataforma paga (https://www.ibm.com/cloud-computing/bluemix/pricing). 

Estaría bueno que la charla no esté centrada en una solución paga de una empresa, porque estás haciendo publicidad encubierta e IBM no es sponsor nuestro.

Entiendo que pueda ser útil para lo que decís, pero herramientas que resuelven ese tipo de problemas, gratuitas y open source existen varias.

**Comment by FMGordillo** [comment]
@nhquiroz También lo es Azure y AWS y sin embargo mucha gente lo usa.

El objetivo de mi charla es **darles algo que yo conozco bien**, y tuve experiencia, **y compartirla**. No quiero incentivar a nadie a usarlo, ni mucho menos a pagar. Pero este año van a haber muchas hackatones y estas plataformas (PaaS) agregan mucho valor.

De última compartime por Slack (mi usuario es el mismo que acá) y pasame esas herramientas, y fusiono mi charla con lo que me decis. Tiempo hay

Cualquier cosa preguntamos si no da esta charla, pero mi intención es compartir, no vender ni hacer branding.

PD.: La Versión de Prueba son 30 días de muchísimo uso tanto en aplicaciones como en servicios (como Watson, que son cognitivos), y luego está "Pay-As-You-Go" o "Adaptación progresiva", que te dan 512 MB de instancia gratuito, perfecto para hacer pruebas en Node Js por poner un ejemplo.
![image](https://cloud.githubusercontent.com/assets/7970174/23885063/93b96058-084f-11e7-83de-a868c59eaec8.png)

**Comment by FMGordillo** [comment]
Colgué por completo de esto jajaja este domingo no puedo, podemos pasarlo para el próximo? O cualquier otro !

**Comment by lndgalante** [comment]
Si, tranqui estan todas las charlas pausadas momentaneamente debido a falta de lugar
