### ISSUE TITLE
Intro a funcional - Norman Perrin

### ISSUE THREAD

**Issue by NormanPerrin** [FreeCodeCampBA/charlas#8]
## Descripción:
Explicación de algunos conceptos básicos y que van de la mano con este paradigma ( Inmutabilidad, Transparencia referencial, Aplicación parcial, Orden superior y Composición de funciones ).

## Autor:
- Nombre: Norman Perrin
- Twitter: [@normanperrinok](https://twitter.com/NormanPerrinOK)

**Comment by Lhoms** [comment]
#aguanteNorman

**Comment by MaximilianoCaba** [comment]
#aguanteNorman
